"""add roadmap_templates and study_plans.skill_name

Revision ID: 6b2b83358f2c
Revises: 78988e3b9499
Create Date: 2026-08-10 00:25:31.099807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2b83358f2c'
down_revision = '78988e3b9499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('resource_hint', sa.String(length=300), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadmap_templates')
    # ### end Alembic commands ###
