"""Initial baseline schema

Revision ID: 78988e3b9499
Revises: 
Create Date: 2026-07-21 18:16:00.976033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78988e3b9499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    with op.batch_alter_table('skill_verifications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'skills', ['skill_id'], ['id'])
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_verifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
