"""add skill_name to study_plans

Revision ID: a73feca05fa9
Revises: 6b2b83358f2c
Create Date: 2026-08-10 23:19:03.958041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73feca05fa9'
down_revision = '6b2b83358f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_column('skill_name')

    # ### end Alembic commands ###
